apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tanmaysama/sre-test'
    targetRevision: HEAD
    path: metrics-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
