{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
data:
  PASSWORD: {{ .Values.secrets.data.PASSWORD | b64enc | quote }}
{{- end }}
